# Generated by Django 3.1.3 on 2020-11-23 20:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('auctions', '0004_auto_20201123_1955'),
    ]

    operations = [
        migrations.AlterField(
            model_name='auction',
            name='current_bid',
            field=models.IntegerField(default=1.0),
        ),
    ]
