# Generated by Django 3.1.3 on 2020-11-24 05:28

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('auctions', '0012_auto_20201124_0525'),
    ]

    operations = [
        migrations.RenameField(
            model_name='auction',
            old_name='starting_bid',
            new_name='current_bid',
        ),
    ]
