# Generated by Django 3.1.3 on 2020-11-25 18:06

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('auctions', '0014_auto_20201124_0528'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='auction',
            name='bids',
        ),
        migrations.RemoveField(
            model_name='user',
            name='listings',
        ),
        migrations.RemoveField(
            model_name='user',
            name='watched',
        ),
        migrations.AddField(
            model_name='auction',
            name='watched_by',
            field=models.ManyToManyField(blank=True, related_name='watching', to=settings.AUTH_USER_MODEL),
        ),
    ]
