# Generated by Django 3.1.3 on 2020-11-25 18:10

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('auctions', '0015_auto_20201125_1806'),
    ]

    operations = [
        migrations.AlterField(
            model_name='auction',
            name='watched_by',
            field=models.ManyToManyField(blank=True, related_name='watched', to=settings.AUTH_USER_MODEL),
        ),
    ]
