# Generated by Django 3.1.3 on 2020-11-25 18:25

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('auctions', '0016_auto_20201125_1810'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='auction',
            name='watched_by',
        ),
        migrations.AddField(
            model_name='user',
            name='watched',
            field=models.ManyToManyField(blank=True, related_name='watched_by', to='auctions.Auction'),
        ),
        migrations.AlterField(
            model_name='auction',
            name='user_id',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='listings', to=settings.AUTH_USER_MODEL),
        ),
    ]
