# Generated by Django 3.1.3 on 2020-11-27 19:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('auctions', '0017_auto_20201125_1825'),
    ]

    operations = [
        migrations.AlterField(
            model_name='auction',
            name='image',
            field=models.ImageField(default='default.png', upload_to='auction_imgs'),
        ),
    ]
